name: Update Repository

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git curl jq

      - name: Setup repository
        run: |
          mkdir -p repo/x86_64

      - name: Download package from latest release
        run: |
          cd repo/x86_64
          
          # Get latest release
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          
          # Find package file
          PACKAGE_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | endswith(".pkg.tar.zst")) | .browser_download_url')
          PACKAGE_NAME=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | endswith(".pkg.tar.zst")) | .name')
          
          if [ "$PACKAGE_URL" != "null" ]; then
            echo "Downloading: $PACKAGE_NAME"
            curl -L -o "$PACKAGE_NAME" "$PACKAGE_URL"
          else
            echo "No package found in release"
            exit 1
          fi

      - name: Create repository database
        run: |
          cd repo/x86_64
          repo-add hyprland-fork.db.tar.gz *.pkg.tar.zst
          ln -sf hyprland-fork.db.tar.gz hyprland-fork.db

      - name: Create index page
        run: |
          cd repo
          cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Hyprland Fork Repository</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .container { max-width: 800px; margin: 0 auto; }
        pre { background: #f5f5f5; padding: 15px; border-radius: 5px; }
        code { background: #e8e8e8; padding: 2px 4px; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Hyprland Fork Repository</h1>
        <p>Custom Arch Linux repository for Hyprland with modifications.</p>
        
        <h2>Setup</h2>
        <p>Add to your <code>/etc/pacman.conf</code>:</p>
        <pre>[hyprland-fork]
Server = https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/repo/$arch</pre>
        
        <p>Then install:</p>
        <pre>sudo pacman -Sy hyprland-fork</pre>
        
        <h2>Package</h2>
        <ul>
            <li><strong>hyprland-fork</strong> - Hyprland with custom modifications</li>
        </ul>
    </div>
</body>
</html>
EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
