name: Update Repository
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git curl jq

      - name: Setup repository
        run: |
          mkdir -p repo/x86_64

      - name: Download package from latest release
        run: |
          cd repo/x86_64
          
          # Get latest release
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          
          echo "Release info: $RELEASE_INFO"
          
          # Find package file
          PACKAGE_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | endswith(".pkg.tar.zst")) | .browser_download_url')
          PACKAGE_NAME=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | endswith(".pkg.tar.zst")) | .name')
          
          echo "Package URL: $PACKAGE_URL"
          echo "Package Name: $PACKAGE_NAME"
          
          if [ "$PACKAGE_URL" != "null" ] && [ -n "$PACKAGE_NAME" ]; then
            echo "Downloading: $PACKAGE_NAME"
            curl -L -o "$PACKAGE_NAME" "$PACKAGE_URL"
            
            # Create repository database
            repo-add hyprland-fork.db.tar.xz *.pkg.tar.zst
          else
            echo "No package found in release"
            echo "Available assets:"
            echo "$RELEASE_INFO" | jq -r '.assets[].name'
            exit 1
          fi

      - name: Create index page
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          cd repo
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hyprland Fork Repository</title>
          </head>
          <body>
              <h1>Hyprland Fork Repository</h1>
              <p>Custom Arch Linux repository for Hyprland with modifications.</p>
              
              <h2>Setup</h2>
              <p>Add to your /etc/pacman.conf:</p>
              <pre>
          [hyprland-fork]
          Server = https://${REPO_OWNER}.github.io/${REPO_NAME}/repo/$arch
              </pre>
              
              <p>Then install:</p>
              <pre>sudo pacman -Sy hyprland-fork</pre>
              
              <h2>Package</h2>
              <ul>
                  <li>hyprland-fork - Hyprland with custom modifications</li>
              </ul>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
