# .github/workflows/update-repository.yml
name: Update Custom Arch Repository

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  PACKAGE_NAME: hyprland-fork

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git curl jq

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup repository structure
        run: |
          mkdir -p repo/x86_64

      - name: Download latest package from release
        run: |
          echo "🔍 Finding latest release..."
          
          # Get latest release info
          RELEASE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          
          echo "Latest release data:"
          echo "$RELEASE_DATA" | jq .
          
          # Extract package download URL
          PACKAGE_URL=$(echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name | endswith(".pkg.tar.zst")) | .browser_download_url')
          PACKAGE_NAME=$(echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name | endswith(".pkg.tar.zst")) | .name')
          
          if [ "$PACKAGE_URL" = "null" ] || [ -z "$PACKAGE_URL" ]; then
            echo "❌ No package found in latest release"
            echo "Available assets:"
            echo "$RELEASE_DATA" | jq -r '.assets[].name'
            exit 1
          fi
          
          echo "📦 Downloading package: $PACKAGE_NAME"
          echo "🔗 URL: $PACKAGE_URL"
          
          cd repo/x86_64
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o "$PACKAGE_NAME" "$PACKAGE_URL"
          
          # Verify download
          if [ ! -f "$PACKAGE_NAME" ]; then
            echo "❌ Failed to download package"
            exit 1
          fi
          
          echo "✅ Package downloaded successfully"
          ls -la "$PACKAGE_NAME"

      - name: Create repository database
        run: |
          cd repo/x86_64
          echo "🗄️ Creating repository database..."
          
          # Remove old database files if they exist
          rm -f *.db* *.files*
          
          # Create new repository database
          repo-add ${{ env.PACKAGE_NAME }}.db.tar.gz *.pkg.tar.zst
          
          # Create symlinks for cleaner URLs
          ln -sf ${{ env.PACKAGE_NAME }}.db.tar.gz ${{ env.PACKAGE_NAME }}.db
          ln -sf ${{ env.PACKAGE_NAME }}.files.tar.gz ${{ env.PACKAGE_NAME }}.files
          
          echo "✅ Repository database created"
          ls -la

      - name: Generate repository index page
        run: |
          cd repo
          
          # Get repository info
          REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          CURRENT_DATE=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          
          # Count packages
          PACKAGE_COUNT=$(ls x86_64/*.pkg.tar.zst 2>/dev/null | wc -l)
          
          cat > index.html << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hyprland Fork Repository</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
        
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
        }
        
        .card {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            border-radius: 15px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            padding: 40px;
            margin-bottom: 30px;
        }
        
        h1 {
            color: #2c3e50;
            font-size: 2.5em;
            margin-bottom: 20px;
            text-align: center;
        }
        
        .subtitle {
            text-align: center;
            color: #7f8c8d;
            font-size: 1.2em;
            margin-bottom: 40px;
        }
        
        .setup-section {
            background: #f8f9fa;
            border-radius: 10px;
            padding: 30px;
            margin: 30px 0;
            border-left: 5px solid #3498db;
        }
        
        .setup-section h2 {
            color: #2c3e50;
            margin-bottom: 20px;
            font-size: 1.5em;
        }
        
        code {
            background: #e9ecef;
            padding: 4px 8px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }
        
        pre {
            background: #2c3e50;
            color: #ecf0f1;
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 15px 0;
            font-family: 'Courier New', monospace;
        }
        
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 30px 0;
        }
        
        .stat-card {
            background: linear-gradient(135deg, #3498db, #2980b9);
            color: white;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
        }
        
        .stat-number {
            font-size: 2em;
            font-weight: bold;
        }
        
        .stat-label {
            font-size: 0.9em;
            opacity: 0.9;
        }
        
        .package-list {
            background: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }
        
        .package-item {
            display: flex;
            align-items: center;
            padding: 15px;
            background: white;
            margin: 10px 0;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        
        .package-name {
            font-weight: bold;
            color: #2c3e50;
            flex-grow: 1;
        }
        
        .package-desc {
            color: #7f8c8d;
            margin-left: 20px;
        }
        
        .footer {
            text-align: center;
            padding: 20px;
            color: #7f8c8d;
            font-size: 0.9em;
        }
        
        .badge {
            display: inline-block;
            background: #27ae60;
            color: white;
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 0.8em;
            margin-left: 10px;
        }
        
        .warning {
            background: #fff3cd;
            border: 1px solid #ffeaa7;
            border-radius: 8px;
            padding: 15px;
            margin: 20px 0;
            color: #856404;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <h1>🚀 Hyprland Fork Repository</h1>
            <p class="subtitle">Custom Arch Linux repository for Hyprland with personal modifications</p>
            
            <div class="stats">
                <div class="stat-card">
                    <div class="stat-number">$PACKAGE_COUNT</div>
                    <div class="stat-label">Available Packages</div>
                </div>
                <div class="stat-card">
                    <div class="stat-number">24/7</div>
                    <div class="stat-label">Auto-Sync</div>
                </div>
                <div class="stat-card">
                    <div class="stat-number">x86_64</div>
                    <div class="stat-label">Architecture</div>
                </div>
            </div>
        </div>
        
        <div class="card">
            <div class="setup-section">
                <h2>📋 Setup Instructions</h2>
                <p>Add the following to your <code>/etc/pacman.conf</code>:</p>
                <pre>[hyprland-fork]
Server = $REPO_URL/repo/\$arch</pre>
                
                <p>Then update your package database and install:</p>
                <pre>sudo pacman -Sy
sudo pacman -S ${{ env.PACKAGE_NAME }}</pre>
                
                <div class="warning">
                    <strong>⚠️ Note:</strong> This package conflicts with the official <code>hyprland</code> package. 
                    Installing <code>${{ env.PACKAGE_NAME }}</code> will replace the official version.
                </div>
            </div>
        </div>
        
        <div class="card">
            <h2>📦 Available Packages</h2>
            <div class="package-list">
                <div class="package-item">
                    <div class="package-name">${{ env.PACKAGE_NAME }}</div>
                    <div class="package-desc">Hyprland with custom modifications</div>
                    <span class="badge">Auto-Updated</span>
                </div>
            </div>
        </div>
        
        <div class="card">
            <h2>🔄 How It Works</h2>
            <ul style="padding-left: 20px; line-height: 2;">
                <li><strong>Automatic Sync:</strong> Checks for upstream Hyprland changes every 6 hours</li>
                <li><strong>Smart Merging:</strong> Automatically merges your modifications with upstream</li>
                <li><strong>Conflict Resolution:</strong> Creates GitHub issues when manual intervention is needed</li>
                <li><strong>Seamless Updates:</strong> Use <code>pacman -Syu</code> to get the latest builds</li>
            </ul>
        </div>
        
        <div class="card">
            <h2>🔗 Links</h2>
            <p><strong>Repository:</strong> <a href="https://github.com/${{ github.repository }}">https://github.com/${{ github.repository }}</a></p>
            <p><strong>Original Hyprland:</strong> <a href="https://github.com/hyprwm/Hyprland">https://github.com/hyprwm/Hyprland</a></p>
            <p><strong>Issues & Support:</strong> <a href="https://github.com/${{ github.repository }}/issues">GitHub Issues</a></p>
        </div>
    </div>
    
    <div class="footer">
        <p>Last updated: $CURRENT_DATE</p>
        <p>Generated automatically by GitHub Actions</p>
    </div>
</body>
</html>
EOF
          
          echo "✅ Repository index page created"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update repository: ${{ github.event.release.tag_name || github.sha }}'

      - name: Repository Status
        run: |
          echo "🎉 Repository updated successfully!"
          echo "📍 Repository URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/repo/\$arch"
          echo "📦 Add to pacman.conf:"
          echo ""
          echo "[hyprland-fork]"
          echo "Server = https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/repo/\$arch"
          echo ""
          echo "Then run: sudo pacman -Sy && sudo pacman -S ${{ env.PACKAGE_NAME }}"
